version: '3.9'

services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/djangoapp/staticfiles
      - media_volume:/djangoapp/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./dotenv_files/.env.prod
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env.prod

volumes:
  db_data:
  static_volume:
  media_volume:


