# Generated by Django 4.2.15 on 2024-09-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football_fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='confirmed', max_length=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('football_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='football_fields.footballfield')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
