# Generated by Django 4.2.14 on 2024-08-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='confirmed', max_length=10),
        ),
    ]
