# Generated by Django 4.2.14 on 2024-08-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_one', models.CharField(max_length=300)),
                ('address_two', models.CharField(max_length=300)),
                ('state', models.CharField(choices=[('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('MG', 'Minas Gerais')], max_length=2)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=50)),
                ('cep_code', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='FootballField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Campo', max_length=100)),
                ('field_dimension', models.CharField(blank=True, max_length=9, null=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football_fields.address')),
            ],
        ),
    ]
