# Generated by Django 4.2.14 on 2024-08-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_two',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
