# Generated by Django 4.2.14 on 2024-08-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_fields', '0002_alter_address_address_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballfield',
            name='field_dimension',
        ),
        migrations.AddField(
            model_name='footballfield',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='footballfield',
            name='facilities',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='footballfield',
            name='field_dimensions',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='footballfield',
            name='grass_type',
            field=models.CharField(choices=[('SIN', 'Sintético'), ('NAT', 'Natural'), ('HIB', 'Híbrido')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='footballfield',
            name='has_changing_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footballfield',
            name='has_field_lighting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footballfield',
            name='hour_price',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='footballfield',
            name='rules',
            field=models.TextField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('MG', 'Minas Gerais')], default='', max_length=2),
        ),
    ]
