# Generated by Django 4.2.15 on 2024-09-17 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football_fields', '0003_footballfield_is_active_footballfield_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballfield',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
