# Generated by Django 4.2.14 on 2024-08-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_fields', '0003_remove_footballfield_field_dimension_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballfield',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='football_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football_fields.footballfield'),
        ),
    ]
