# Generated by Django 4.2.15 on 2024-09-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_fields', '0004_alter_footballfield_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballfield',
            name='main_image',
            field=models.ImageField(upload_to='football_fields_images'),
        ),
    ]
