# Generated by Django 4.2.14 on 2024-08-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_fields', '0005_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='football_fields_images')),
                ('football_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_fields.footballfield')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='football_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='football_fields.footballfield'),
        ),
        migrations.DeleteModel(
            name='Attachments',
        ),
    ]
