# Generated by Django 4.2.14 on 2024-08-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_fields', '0006_attachment_alter_address_football_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballfield',
            name='grass_type',
            field=models.CharField(choices=[('SIN', 'Sintético'), ('NAT', 'Natural'), ('HIB', 'Híbrido')], default='SIN', max_length=3),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='has_changing_room',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='has_field_lighting',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='footballfield',
            name='hour_price',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
