# Generated by Django 4.2.14 on 2024-08-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_fields', '0007_alter_footballfield_grass_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballfield',
            name='hour_price',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
