# Generated by Django 4.2.14 on 2024-08-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_fields', '0009_footballfield_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
